### PR TITLE
ADD 2D option

### PR DESCRIPTION
**Pull request by UBaer21**
thickness = 0 will return a 2D code that can be used.

### CODE REVIEW

**Comment by xypwn** [comment]
Hi,
thanks for taking the time to submit a PR, but after reviewing the code, there are multiple issues I've noticed.
- You directly edited `qr.scad`, which is an automatically generated file not to be edited. The source files, which should be edited are found in the src/ directory. This is also explained in [README.md#Development](https://github.com/xypwn/scadqr?tab=readme-ov-file#development)
- You used Windows CRLF line endings, while this repo uses Unix LF. This makes it impossible for the diff to show which changes were actually made, since every line is technically changed.
- Your approach uses a global `$3D` variable, which is opposed to the more functional style of writing code I use in this repo. I prefer a functional style because it makes it easier to reconstruct the path a value takes throughout all function calls, thus making the code more readable and understandable. A more functional approach to this problem could be, for example, to have `qr()` use a different set of default elements, which are 2D instead of 3D when thickness == 0.

**Comment by UBaer21** [comment]
I used openSCAD to edit the .scad not sure why github can't handle this proper. Using a special variable was the easiest way without adding new variables on each module, as you switched to 3D already in your "helper" modules and then scaled instead of using offset() for epsilon (which btw is causing problems with the dev versions of scad and manifold but we have already an issue open for that). But it in general it would be cleaner to keep everything in 2D and then extrude at top-level.  However as you made such a useful code i thought you maybe want to add the option, how ever you like to code that - as QR code is 2D.

**Comment by xypwn** [comment]
You can use an external editor like notepad++ (which can be set to LF) to edit the file, and OpenSCAD should automatically update the preview after each save. AFAIK, GitHub doesn't ever change the line ending.

Technically speaking, 2D QR codes are already possible by using `qr_custom()` with 2D elements.

But I agree that QR codes are 2D objects, and that a simple 2D option could definitely be useful. Extruding everything at top-level would probably be the most desirable approach, in the end, especially when also considering the implications this might have on the renderer.

**Comment by xypwn** [comment]
I went ahead and implemented the feature in a way that I find is more consistent with the rest of the codebase. A QR code is now made 2D by setting the `thickness` parameter to 0.
Thanks for suggesting this feature :)

**Pull request closed without merging**
